package io.github.lucasduete.view;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.io.ParseException;
import com.vividsolutions.jts.io.WKTReader;
import io.github.lucasduete.controller.Calculator;
import io.github.lucasduete.controller.ImageFactory;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {
    
    private void setNamesTable() {
        
        jTable1.setValueAt("A Equals B", 0, 0);
        jTable1.setValueAt("B Equals A", 1, 0);
        jTable1.setValueAt("A Disjoint B", 2, 0);
        jTable1.setValueAt("B Disjoint A", 3, 0);
        jTable1.setValueAt("A Intersect B", 4, 0);
        jTable1.setValueAt("B Intersect A", 5, 0);
        jTable1.setValueAt("A Touchs B", 6, 0);
        jTable1.setValueAt("B Touchs A", 7, 0);
        jTable1.setValueAt("A Crosses B", 8, 0);
        jTable1.setValueAt("B Crosses A", 9, 0);
        jTable1.setValueAt("A Within B", 10, 0);
        jTable1.setValueAt("B Within A", 11, 0);
        jTable1.setValueAt("A Contains B", 12, 0);
        jTable1.setValueAt("B Contains A", 13, 0);
        jTable1.setValueAt("A Overlaps B", 14, 0);
        jTable1.setValueAt("B Overlaps A", 15, 0);
        jTable1.setValueAt("A Covers B", 16, 0);
        jTable1.setValueAt("B Covers A", 17, 0);
        jTable1.setValueAt("A CoveredBy B", 18, 0);
        jTable1.setValueAt("B CoveredBy A", 19, 0);
        
    }
    
    private void polulateTable(Geometry A, Geometry B) {
        jTable1.setValueAt(Calculator.equalsAB(A, B), 0, 1);
        jTable1.setValueAt(Calculator.equalsBA(B, A), 1, 1);        
        
        jTable1.setValueAt(Calculator.disjointAB(A, B), 2, 1);
        jTable1.setValueAt(Calculator.disjointBA(B, A), 3, 1);
        
        jTable1.setValueAt(Calculator.intersectsAB(A, B), 4, 1);
        jTable1.setValueAt(Calculator.intersectsBA(B, A), 5, 1);
        
        
        jTable1.setValueAt(Calculator.touchsAB(A, B), 6, 1);
        jTable1.setValueAt(Calculator.touchsBA(B, A), 7, 1);
        
        
        jTable1.setValueAt(Calculator.crossesAB(A, B), 8, 1);
        jTable1.setValueAt(Calculator.crossesBA(B, A), 9, 1);
        
        
        jTable1.setValueAt(Calculator.withinAB(A, B), 10, 1);
        jTable1.setValueAt(Calculator.withinBA(B, A), 11, 1);
        
        
        jTable1.setValueAt(Calculator.containsAB(A, B), 12, 1);
        jTable1.setValueAt(Calculator.containsBA(B, A), 13, 1);
        
        
        jTable1.setValueAt(Calculator.overlapsAB(A, B), 14, 1);
        jTable1.setValueAt(Calculator.overlapsBA(B, A), 15, 1);
        
        
        jTable1.setValueAt(Calculator.coversAB(A, B), 16, 1);
        jTable1.setValueAt(Calculator.coversBA(B, A), 17, 1);
        
        
        jTable1.setValueAt(Calculator.coveredByAB(A, B), 18, 1);
        jTable1.setValueAt(Calculator.coveredByBA(B, A), 19, 1);
    }

    /**
     * Creates new form main
     */
    public Home() {
        initComponents();
        setNamesTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Geometria 1");

        jLabel2.setText("Geometria 2");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Condiçao", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        final Geometry A;
        final Geometry B;
        final WKTReader reader = new WKTReader();
        
        try {            
            A = reader.read(jTextField1.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Geometria 1 Invalida", "Dados Invalidos", JOptionPane.INFORMATION_MESSAGE);
            ex.printStackTrace();
            return;
        }
        
        try {            
            B = reader.read(jTextField2.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Geometria 2 Invalida", "Dados Invalidos", JOptionPane.INFORMATION_MESSAGE);
            ex.printStackTrace();
            return;
        }
        
       
        polulateTable(A, B);
        ImageFactory.GeneratePNG(A, B);
        ImageFactory.GenerateSVG(A, B);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
